*--------------------------------------------------------------------------------;
* Add information about family psychiatric history                               ;
*--------------------------------------------------------------------------------;

*-Exposure: ASD conditions among mothers + Covariate: psychiatric conditions among mothers;
proc sort data=ana2; by mother; run;
proc sort data=h2; by condition lopnr; run;


*- ASD among mothers;
data ana3;
 drop icd diag any_psych condition asd;
 length mom_ASD 3;
 merge ana2 (in=ana2) h2 (in=h2 rename=(lopnr=mother diag_dat=mom_diagdat) where=(condition = 'ASD'));
 by mother;
 if h2 then mom_ASD=1; 
 * if h2 and mom_diagdat lt child_birth_dat then mom_ASD=1; **Select those diagnosed before child's birth date**;
 else mom_ASD=0;
 if ana2;
run;

*- AD among mothers;
data ana3;
 drop icd diag any_psych condition diag_dat asd;
 length mom_AD 3;
 merge ana3 (in=ana3) h2 (in=h2 rename=(lopnr=mother) where=(condition = 'AD'));
 by mother;
 if h2 then mom_AD=1; 
 * if h2 and diag_dat lt child_birth_dat then mom_AD=1; **Select those diagnosed before child's birth date**;
 else mom_AD=0;
 if ana3;
run;

*- Asperger among mothers;
data ana3;
 drop icd diag any_psych condition diag_dat asd;
 length mom_AS 3;
 merge ana3 (in=ana3) h2 (in=h2 rename=(lopnr=mother) where=(condition = 'AS'));
 by mother;
 if h2 then mom_AS=1; 
 * if h2 and diag_dat lt child_birth_dat then mom_AS=1; **Select those diagnosed before child's birth date**;
 else mom_AS=0;
 if ana3;
run; 

*- PDD-NOS among mothers;
data ana3;
 drop icd diag any_psych condition diag_dat asd;
 length mom_PDD 3;
 merge ana3 (in=ana3) h2 (in=h2 rename=(lopnr=mother) where=(condition = 'PDD'));
 by mother;
 if h2 then mom_PDD=1; 
 * if h2 and diag_dat lt child_birth_dat then mom_PDD=1; **Select those diagnosed before child's birth date**;
 else mom_PDD=0;
 if ana3;
run; 

*- Intellectual disability among mothers;
data ana3;
 drop icd diag any_psych condition diag_dat asd;
 length mom_ID 3;
 merge ana3 (in=ana3) h2 (in=h2 rename=(lopnr=mother) where=(condition = 'ID'));
 by mother;
 if h2 then mom_ID=1; 
 * if h2 and diag_dat lt child_birth_dat then mom_ID=1; **Select those diagnosed before child's birth date**;
 else mom_ID=0;
 if ana3;
run; 

*- Severe intellectual disability among mothers;
data ana3;
 drop icd diag any_psych condition diag_dat asd;
 length mom_SID 3;
 merge ana3 (in=ana3) h2 (in=h2 rename=(lopnr=mother) where=(condition = 'SID'));
 by mother;
 if h2 then mom_SID=1; 
 * if h2 and diag_dat lt child_birth_dat then mom_SID=1; **Select those diagnosed before child's birth date**;
 else mom_SID=0;
 if ana3;
run; 

*- Depression among mothers;
data ana3;
 drop icd diag any_psych condition diag_dat asd;
 length mom_DEP 3;
 merge ana3 (in=ana3) h2 (in=h2 rename=(lopnr=mother) where=(condition = 'DEP'));
 by mother;
 if h2 then mom_DEP=1; 
 * if h2 and diag_dat lt child_birth_dat then mom_DEP=1; **Select those diagnosed before child's birth date**;
 else mom_DEP=0;
 if ana3;
run; 

*- Anxiety disorder among mothers;
data ana3;
 drop icd diag any_psych condition diag_dat asd;
 length mom_ANX 3;
 merge ana3 (in=ana3) h2 (in=h2 rename=(lopnr=mother) where=(condition = 'ANX'));
 by mother;
 if h2 then mom_ANX=1; 
 * if h2 and diag_dat lt child_birth_dat then mom_ANX=1; **Select those diagnosed before child's birth date**;
 else mom_ANX=0;
 if ana3;
run; 

*- Substance use disorder among mothers;
data ana3;
 drop icd diag any_psych condition diag_dat asd;
 length mom_SUB 3;
 merge ana3 (in=ana3) h2 (in=h2 rename=(lopnr=mother) where=(condition = 'SUB'));
 by mother;
 if h2 then mom_SUB=1; 
 * if h2 and diag_dat lt child_birth_dat then mom_SUB=1; **Select those diagnosed before child's birth date**;
 else mom_SUB=0;
 if ana3;
run; 

*- Bipolar disorder among mothers;
data ana3;
 drop icd diag any_psych condition diag_dat asd;
 length mom_BIP 3;
 merge ana3 (in=ana3) h2 (in=h2 rename=(lopnr=mother) where=(condition = 'BIP'));
 by mother;
 if h2 then mom_BIP=1; 
 * if h2 and diag_dat lt child_birth_dat then mom_BIP=1; **Select those diagnosed before child's birth date**;
 else mom_BIP=0;
 if ana3;
run; 

*- Compulsive disorder among mothers;
data ana3;
 drop icd diag any_psych condition diag_dat asd;
 length mom_COM 3;
 merge ana3 (in=ana3) h2 (in=h2 rename=(lopnr=mother) where=(condition = 'COM'));
 by mother;
 if h2 then mom_COM=1; 
 * if h2 and diag_dat lt child_birth_dat then mom_COM=1; **Select those diagnosed before child's birth date**;
 else mom_COM=0;
 if ana3;
run; 

*- ADHD among mothers;
data ana3;
 drop icd diag any_psych condition diag_dat asd;
 length mom_ADHD 3;
 merge ana3 (in=ana3) h2 (in=h2 rename=(lopnr=mother) where=(condition = 'ADH'));
 by mother;
 if h2 then mom_ADHD=1; 
 * if h2 and diag_dat lt child_birth_dat then mom_ADHD=1; **Select those diagnosed before child's birth date**;
 else mom_ADHD=0;
 if ana3;
run; 

*- Affective disorder among mothers;
data ana3;
 drop icd diag any_psych condition diag_dat asd;
 length mom_AFF 3;
 merge ana3 (in=ana3) h2 (in=h2 rename=(lopnr=mother) where=(condition = 'AFF'));
 by mother;
 if h2 then mom_AFF=1; 
 * if h2 and diag_dat lt child_birth_dat then mom_AFF=1; **Select those diagnosed before child's birth date**;
 else mom_AFF=0;
 if ana3;
run; 

*- Schizophrenia among mothers;
data ana3;
 drop icd diag any_psych condition diag_dat asd;
 length mom_SCH 3;
 merge ana3 (in=ana3) h2 (in=h2 rename=(lopnr=mother) where=(condition = 'SCH'));
 by mother;
 if h2 then mom_SCH=1; 
 * if h2 and diag_dat lt child_birth_dat then mom_SCH=1; **Select those diagnosed before child's birth date**;
 else mom_SCH=0;
 if ana3;
run; 

*- Schizoid personality disorder among mothers;
data ana3;
 drop icd diag any_psych condition diag_dat asd;
 length mom_SPD 3;
 merge ana3 (in=ana3) h2 (in=h2 rename=(lopnr=mother) where=(condition = 'SPD'));
 by mother;
 if h2 then mom_SPD=1; 
 * if h2 and diag_dat lt child_birth_dat then mom_SPD=1; **Select those diagnosed before child's birth date**;
 else mom_SPD=0;
 if ana3;
run; 

*- Any mental illness among mothers;
proc sort data=h3; by lopnr; run;
data ana3;
 drop icd diag any_psych diag_dat;
 length mom_PSYCH 3;
 merge ana3 (in=ana3) h3 (in=h3 rename=(lopnr=mother));
 by mother;
 if h3 then mom_PSYCH=1; 
 * if h3 and diag_dat lt child_birth_dat then mom_PSYCH=1; **Select those diagnosed before child's birth date**;
 else mom_PSYCH=0;
 if ana3;
run; 
